export enum Direction {
  Up = "Up",
  Down = "Down",
  Left = "Left",
  Right = "Right",
  UpDown = Up + Down,
  DownUp = Down + Up,
  UpLeft = Up + Left,
  UpRight = Up + Right,
  DownLeft = Down + Left,
  DownRight = Down + Right,
  LeftRight = Left + Right,
  RightLeft = Right + Left,
  LeftUp = Left + Up,
  RightUp = Right + Up,
  LeftDown = Left + Down,
  RightDown = Right + Down
}

export enum Operations {
  Invalid = "invalidOperation",
  ScrollUp = "scrollUp",
  ScrollDown = "scrollDown",
  ScrollLeft = "scrollLeft",
  ScrollRight = "scrollRight",
  ScrollToTop = "scrollToTop",
  ScrollToBottom = "scrollToBottom",
  Backward = "backward",
  Forward = "forward",
  Refresh = "refresh",
  ReloadAllTabs = "reloadAllTabs",
  OpenNewTab = "openNewTab",
  OpenIncognitoWindow = "openIncognitoWindow",
  CloseCurrentTab = "closeCurrentTab",
  CloseOtherTabs = "closeOtherTabs",
  CloseAllTabs = "closeAllTabs",
  CloseWindow = "closeWindow",
  ReopenLastClosedTab = "reopenLastClosedTab",
  SwitchLeftTab = "switchLeftTab",
  SwitchRightTab = "switchRightTab",
  Fullscreen = "fullscreen",
  MinimizeWindow = "minimizeWindow",
}